/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'
import { Route as DemoMcpTodosRouteImport } from './routes/demo/mcp-todos'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard/projects/index'
import { Route as DashboardHomeIndexRouteImport } from './routes/dashboard/home/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoApiMcpTodosRouteImport } from './routes/demo/api.mcp-todos'
import { Route as DashboardSettingsBasicRouteImport } from './routes/dashboard/settings/basic'
import { Route as DashboardSettingsAuthRouteImport } from './routes/dashboard/settings/auth'
import { Route as DashboardProjectsNewRouteImport } from './routes/dashboard/projects/new'
import { Route as ApiSettingsAccountRouteImport } from './routes/api/settings/account'
import { Route as ApiProjectsIdRouteImport } from './routes/api/projects.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardProjectsIdRouteRouteImport } from './routes/dashboard/projects/$id/route'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DashboardProjectsIdIndexRouteImport } from './routes/dashboard/projects/$id/index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as DashboardProjectsIdEditRouteImport } from './routes/dashboard/projects/$id/edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMcpTodosRoute = DemoMcpTodosRouteImport.update({
  id: '/demo/mcp-todos',
  path: '/demo/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHomeIndexRoute = DashboardHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiMcpTodosRoute = DemoApiMcpTodosRouteImport.update({
  id: '/demo/api/mcp-todos',
  path: '/demo/api/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsBasicRoute = DashboardSettingsBasicRouteImport.update({
  id: '/settings/basic',
  path: '/settings/basic',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsAuthRoute = DashboardSettingsAuthRouteImport.update({
  id: '/settings/auth',
  path: '/settings/auth',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjectsNewRoute = DashboardProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiSettingsAccountRoute = ApiSettingsAccountRouteImport.update({
  id: '/api/settings/account',
  path: '/api/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdRoute = ApiProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProjectsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsIdRouteRoute =
  DashboardProjectsIdRouteRouteImport.update({
    id: '/projects/$id',
    path: '/projects/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsIdIndexRoute =
  DashboardProjectsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectsIdRouteRoute,
  } as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsIdEditRoute = DashboardProjectsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DashboardProjectsIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/api/settings/account': typeof ApiSettingsAccountRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/settings/auth': typeof DashboardSettingsAuthRoute
  '/dashboard/settings/basic': typeof DashboardSettingsBasicRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/dashboard/home': typeof DashboardHomeIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/projects/$id/edit': typeof DashboardProjectsIdEditRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/dashboard/projects/$id/': typeof DashboardProjectsIdIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/api/settings/account': typeof ApiSettingsAccountRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/settings/auth': typeof DashboardSettingsAuthRoute
  '/dashboard/settings/basic': typeof DashboardSettingsBasicRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/dashboard/home': typeof DashboardHomeIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/projects/$id/edit': typeof DashboardProjectsIdEditRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/api/settings/account': typeof ApiSettingsAccountRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/settings/auth': typeof DashboardSettingsAuthRoute
  '/dashboard/settings/basic': typeof DashboardSettingsBasicRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/dashboard/home/': typeof DashboardHomeIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/projects/$id/edit': typeof DashboardProjectsIdEditRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/dashboard/projects/$id/': typeof DashboardProjectsIdIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/api/projects'
    | '/demo/mcp-todos'
    | '/demo/prisma'
    | '/dashboard/'
    | '/dashboard/projects/$id'
    | '/api/auth/$'
    | '/api/projects/$id'
    | '/api/settings/account'
    | '/dashboard/projects/new'
    | '/dashboard/settings/auth'
    | '/dashboard/settings/basic'
    | '/demo/api/mcp-todos'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/dashboard/home'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/projects/$id/edit'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/dashboard/projects/$id/'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/api/projects'
    | '/demo/mcp-todos'
    | '/demo/prisma'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/projects/$id'
    | '/api/settings/account'
    | '/dashboard/projects/new'
    | '/dashboard/settings/auth'
    | '/dashboard/settings/basic'
    | '/demo/api/mcp-todos'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/dashboard/home'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/projects/$id/edit'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/dashboard/projects/$id'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/api/projects'
    | '/demo/mcp-todos'
    | '/demo/prisma'
    | '/dashboard/'
    | '/dashboard/projects/$id'
    | '/api/auth/$'
    | '/api/projects/$id'
    | '/api/settings/account'
    | '/dashboard/projects/new'
    | '/dashboard/settings/auth'
    | '/dashboard/settings/basic'
    | '/demo/api/mcp-todos'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/dashboard/home/'
    | '/dashboard/projects/'
    | '/dashboard/settings/'
    | '/dashboard/projects/$id/edit'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/dashboard/projects/$id/'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  SignupRoute: typeof SignupRoute
  ApiProjectsRoute: typeof ApiProjectsRouteWithChildren
  DemoMcpTodosRoute: typeof DemoMcpTodosRoute
  DemoPrismaRoute: typeof DemoPrismaRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSettingsAccountRoute: typeof ApiSettingsAccountRoute
  DemoApiMcpTodosRoute: typeof DemoApiMcpTodosRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mcp-todos': {
      id: '/demo/mcp-todos'
      path: '/demo/mcp-todos'
      fullPath: '/demo/mcp-todos'
      preLoaderRoute: typeof DemoMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/home/': {
      id: '/dashboard/home/'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/mcp-todos': {
      id: '/demo/api/mcp-todos'
      path: '/demo/api/mcp-todos'
      fullPath: '/demo/api/mcp-todos'
      preLoaderRoute: typeof DemoApiMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/basic': {
      id: '/dashboard/settings/basic'
      path: '/settings/basic'
      fullPath: '/dashboard/settings/basic'
      preLoaderRoute: typeof DashboardSettingsBasicRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/auth': {
      id: '/dashboard/settings/auth'
      path: '/settings/auth'
      fullPath: '/dashboard/settings/auth'
      preLoaderRoute: typeof DashboardSettingsAuthRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects/new': {
      id: '/dashboard/projects/new'
      path: '/projects/new'
      fullPath: '/dashboard/projects/new'
      preLoaderRoute: typeof DashboardProjectsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/settings/account': {
      id: '/api/settings/account'
      path: '/api/settings/account'
      fullPath: '/api/settings/account'
      preLoaderRoute: typeof ApiSettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id': {
      id: '/api/projects/$id'
      path: '/$id'
      fullPath: '/api/projects/$id'
      preLoaderRoute: typeof ApiProjectsIdRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects/$id': {
      id: '/dashboard/projects/$id'
      path: '/projects/$id'
      fullPath: '/dashboard/projects/$id'
      preLoaderRoute: typeof DashboardProjectsIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects/$id/': {
      id: '/dashboard/projects/$id/'
      path: '/'
      fullPath: '/dashboard/projects/$id/'
      preLoaderRoute: typeof DashboardProjectsIdIndexRouteImport
      parentRoute: typeof DashboardProjectsIdRouteRoute
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects/$id/edit': {
      id: '/dashboard/projects/$id/edit'
      path: '/edit'
      fullPath: '/dashboard/projects/$id/edit'
      preLoaderRoute: typeof DashboardProjectsIdEditRouteImport
      parentRoute: typeof DashboardProjectsIdRouteRoute
    }
  }
}

interface DashboardProjectsIdRouteRouteChildren {
  DashboardProjectsIdEditRoute: typeof DashboardProjectsIdEditRoute
  DashboardProjectsIdIndexRoute: typeof DashboardProjectsIdIndexRoute
}

const DashboardProjectsIdRouteRouteChildren: DashboardProjectsIdRouteRouteChildren =
  {
    DashboardProjectsIdEditRoute: DashboardProjectsIdEditRoute,
    DashboardProjectsIdIndexRoute: DashboardProjectsIdIndexRoute,
  }

const DashboardProjectsIdRouteRouteWithChildren =
  DashboardProjectsIdRouteRoute._addFileChildren(
    DashboardProjectsIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectsIdRouteRoute: typeof DashboardProjectsIdRouteRouteWithChildren
  DashboardProjectsNewRoute: typeof DashboardProjectsNewRoute
  DashboardSettingsAuthRoute: typeof DashboardSettingsAuthRoute
  DashboardSettingsBasicRoute: typeof DashboardSettingsBasicRoute
  DashboardHomeIndexRoute: typeof DashboardHomeIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectsIdRouteRoute: DashboardProjectsIdRouteRouteWithChildren,
  DashboardProjectsNewRoute: DashboardProjectsNewRoute,
  DashboardSettingsAuthRoute: DashboardSettingsAuthRoute,
  DashboardSettingsBasicRoute: DashboardSettingsBasicRoute,
  DashboardHomeIndexRoute: DashboardHomeIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface ApiProjectsRouteChildren {
  ApiProjectsIdRoute: typeof ApiProjectsIdRoute
}

const ApiProjectsRouteChildren: ApiProjectsRouteChildren = {
  ApiProjectsIdRoute: ApiProjectsIdRoute,
}

const ApiProjectsRouteWithChildren = ApiProjectsRoute._addFileChildren(
  ApiProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  SignupRoute: SignupRoute,
  ApiProjectsRoute: ApiProjectsRouteWithChildren,
  DemoMcpTodosRoute: DemoMcpTodosRoute,
  DemoPrismaRoute: DemoPrismaRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSettingsAccountRoute: ApiSettingsAccountRoute,
  DemoApiMcpTodosRoute: DemoApiMcpTodosRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
